FROM golang:latest AS builder

WORKDIR /go/src/
COPY ./ ./
#RUN go build
RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" ./...

FROM registry.access.redhat.com/ubi8-minimal:latest
LABEL io.openshift.expose-services 8080:http

COPY --from=builder --chown=1001:0 /go/src/api ./
EXPOSE 8080

CMD ["./api"]

